# Generated by Django 2.2.6 on 2019-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
