# Generated by Django 2.2.6 on 2019-11-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_news_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='body',
        ),
    ]
