# Generated by Django 2.2.6 on 2019-11-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191201_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='content',
        ),
    ]
